### ISSUE TITLE
v3.0 New UI

### ISSUE THREAD

**Issue by chadyj** [WalletConnect/web3modal#1131]
Playground components: https://web3modal-gallery.vercel.app/

```[tasklist]
### V3.0 UI Components
- [x] wui-icon (https://web3modal-gallery.vercel.app/?path=/docs/components-wui-icon--docs)
- [x] wui-text (https://web3modal-gallery.vercel.app/?path=/docs/components-wui-text--docs)
- [x] wui-image (https://web3modal-gallery.vercel.app/?path=/docs/components-wui-image--docs)
- [x] wui-card (http://localhost:6006/?path=/docs/components-wui-card--docs)
- [x] wui-shimmer (http://localhost:6006/?path=/docs/components-wui-shimmer--docs)
```

```[tasklist]
### V3.0 UI Composites
- [x] wui-all-wallets-image (https://web3modal-gallery.vercel.app/?path=/docs/composites-wui-all-wallets-image--docs)
- [x] wui-button (https://web3modal-gallery.vercel.app/?path=/docs/composites-wui-button--docs)
- [x] wui-card-select-loader (http://localhost:6006/?path=/docs/composites-wui-card-select-loader--docs)
- [x] wui-card-select (https://web3modal-gallery.vercel.app/?path=/docs/composites-wui-card-select--docs)
- [x] wui-chip (http://localhost:6006/?path=/docs/composites-wui-chip--docs)
- [x] wui-icon-box (https://web3modal-gallery.vercel.app/?path=/docs/composites-wui-icon-box--docs)
- [x] wui-icon-link (http://localhost:6006/?path=/docs/composites-wui-icon-link--docs)
- [x] wui-input-element (http://localhost:6006/?path=/docs/composites-wui-input-element--docs)
- [x] wui-input (http://localhost:6006/?path=/docs/composites-wui-input--docs)
- [x] wui-link (https://web3modal-gallery.vercel.app/?path=/docs/composites-wui-link--docs)
- [x] wui-list-select (https://web3modal-gallery.vercel.app/?path=/docs/composites-wui-list-select--docs)
- [x] wui-loading-spinner (http://localhost:6006/?path=/docs/composites-wui-loading-spinner--docs)
- [x] wui-loading-thumbnail (http://localhost:6006/?path=/docs/composites-wui-loading-thumbnail--docs)
- [x] wui-search-bar (http://localhost:6006/?path=/docs/composites-wui-search-bar--docs)
- [x] wui-snackbar (http://localhost:6006/?path=/docs/composites-wui-snackbar--docs)
- [x] wui-tooltip (http://localhost:6006/?path=/docs/composites-wui-tooltip--docs)
- [x] wui-transaction-visual (http://localhost:6006/?path=/docs/composites-wui-transaction-visual--docs)
- [x] wui-wallet-image (https://web3modal-gallery.vercel.app/?path=/docs/composites-wui-wallet-image--docs)
- [ ] wui-dropdown
- [ ] wui-transaction
- [ ] wui-network-image
```

```[tasklist]
### V3.0 UI Layout
- [x] wui-grid (https://web3modal-gallery.vercel.app/?path=/docs/layout-wui-grid--docs)
- [x] wui-flex (https://web3modal-gallery.vercel.app/?path=/docs/layout-wui-flex--docs)
```

```[tasklist]
### Tasks
- [ ] https://github.com/WalletConnect/web3modal/issues/1065
- [ ] https://github.com/WalletConnect/web3modal/issues/1132
```

**Comment by 0xAsimetriq** [comment]
Implemented in v3
