### ISSUE TITLE
[feature] W3M e2e task list

### ISSUE THREAD

**Issue by JonathanConn** [WalletConnect/web3modal#1243]
Tracking the e2e work for W3M

```[tasklist]
### Tasks
- [ ] https://github.com/WalletConnect/web-examples/pull/240
- [ ] https://github.com/WalletConnect/web-examples/pull/246
- [ ] https://github.com/WalletConnect/web3modal/pull/1226
- [ ] https://github.com/WalletConnect/web-examples/pull/260
- [ ] https://github.com/WalletConnect/web3modal/pull/1248
- [ ] https://github.com/WalletConnect/web3modal/pull/1252
- [ ] https://github.com/WalletConnect/web3modal/pull/1251
- [ ] https://github.com/WalletConnect/web3modal/pull/1254
- [ ] https://github.com/WalletConnect/web3modal/issues/1246
- [ ] https://github.com/WalletConnect/web3modal/issues/1244
- [ ] https://github.com/WalletConnect/web3modal/issues/1245
- [ ] https://github.com/WalletConnect/web3modal/issues/1247
```

**Comment by JonathanConn** [comment]
Remaining two tasks will be completed once the v3 examples are up
These will be examples will be very minimal and will create a much better testing env
