### ISSUE TITLE
Web3Modal v4 reports (Wagmi v2 and others)

### ISSUE THREAD

**Issue by glitch-txs** [WalletConnect/web3modal#1797]
### Link to minimal reproducible example

N/A

### Summary

- [x] Wagmi1 package is not working with the default configuration. https://github.com/WalletConnect/web3modal/issues/1793
- [x] Wagmi v2: Connectors need to be updated (`watchConnectors`)  **P0** https://github.com/WalletConnect/web3modal/issues/1795
- [x] Wagmi v2: server/client error **P0** https://github.com/WalletConnect/web3modal/issues/1796
- [x] Allow to connect with different chains with extension wallets **P0** https://github.com/WalletConnect/web3modal/issues/1782
- [x] Remove `chains` param in `createWeb3Modal` function https://github.com/WalletConnect/web3modal/issues/1794
- [x] Looks like wagmi v2 implementation has various type issues,  related to importing them from `@wagmi/core` / `wagmi` and `viem`. (chains and config)

### List of related npm package versions

N/A

**Comment by tomiir** [comment]
> Wagmi1 package is not working with the default configuration. https://github.com/WalletConnect/web3modal/issues/1793
=> https://github.com/WalletConnect/web3modal/pull/1798

> Wagmi v2: Connectors need to be updated (watchConnectors) P0 
> https://github.com/WalletConnect/web3modal/issues/1795
 => https://github.com/WalletConnect/web3modal/pull/1800

> Remove chains param in createWeb3Modal function https://github.com/WalletConnect/web3modal/issues/1794
=> https://github.com/WalletConnect/web3modal/pull/1801
